---
# tasks file for rtervoort.elasticsearch

- name: Install ElasticSearch package
  yum:
    name: elasticsearch
    state: installed

- name: Configure ElasticSearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: 0644
    force: yes
  notify: restart elasticsearch

- name: Install ElasticSearch X-Pack plugin
  command: >
    /usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack
  args:
    creates: /usr/share/elasticsearch/plugins/x-pack/LICENSE.txt
  notify: restart elasticsearch

- name: ElasticSearch service
  service:
    name: elasticsearch
    state: started
    enabled: true
