---
# tasks file for rtervoort.logstash

- name: Install nginx package
  yum:
    name: nginx
    state: installed

- name: Make sure nginx is started
  service:
    name: nginx
    state: started
    enabled: true
