---
# tasks file for rtervoort.elasticsearch

- name: Install ElasticSearch
  yum:
    name: elasticsearch
    state: latest
  notify: restart elasticsearch

- name: Configure ElasticSearch
  template: 
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml 
    owner: elasticsearch 
    group: elasticsearch
    mode: 0644 
    force: yes
  notify: restart elasticsearch
