---
# tasks file for rtervoort.elastic-repo

- name: Configure elastic repo
  template:
    src=elasticsearch.repo
    dest=/etc/yum.repos.d/elasticsearch-{{ es_major_version }}.repo

- name: Configure logstash repo
  template:
    src=logstash.repo 
    dest=/etc/yum.repos.d/logstash-{{ ls_major_version }}.repo
